#!/bin/bash
cd ./tests
for i in `cat ../test_cases | sort`
do
    echo "########## Testing Ezhil script $i $1" | tee -a ../dump_file    
    echo 'profile("begin")' > foo.n
    cat $i >> foo.n
    echo 'profile("results")' >> foo.n
    python ../ezhil/ezhil.py  foo.n $X 2>&1 >> ../dump_file
    if [ $? -eq 0 ]
    then
       echo $i >> ../success.txt
    else
       echo $i >> ../failed.txt
    fi
    sleep 0
done
